env:
  - VERBOSE=1

language: python

python:
  - "3.6"

install:
  - apt install texlive-latex-base
  - apt install texlive-extra
  - python setup.py install


script:
  - python -m textrain hello world
