sudo:       required
language:   python
services:   docker

script:
- docker pull strauman/travis-latexbuild:small # select small texlive scheme
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind strauman/travis-latexbuild:small # also it here

env:
  - VERBOSE=1

python:
  - "3.6"

install:
  - python setup.py install

script:
  - python -m textrain hello world
