env:
  - VERBOSE=1

language: python

python:
  - "3.6"

before_install:
  - sudo apt install texlive-latex-base
  - sudo apt install texlive-extra

install:
  - python setup.py install


script:
  - python -m textrain hello world
